### ISSUE TITLE
Docker is not building

### ISSUE THREAD

**Issue by madchap** [PearsonEducation/bag-of-holding#26]
Hi,

Checked out HEAD (ba4239c74ccb8247d27ad96b1e2b20289157a3c9) and tried to quickly build the docker image following the README.md, but it fails with the following error:

```
Step 13/14 : RUN python3 /bag-of-holding/project/manage.py makemigrations &&     python3 /bag-of-holding/project/manage.py migrate &&     python3 /bag-of-holding/project/manage.py loaddata /bag-of-holding/project/sample_data.json
 ---> Running in 667fb3963d37
Traceback (most recent call last):
  File "/bag-of-holding/project/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/libs/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/libs/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/libs/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/libs/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/libs/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/libs/django_filters/__init__.py", line 3, in <module>
    from .filterset import FilterSet
  File "/libs/django_filters/filterset.py", line 19, in <module>
    from .filters import (Filter, CharFilter, BooleanFilter, BaseInFilter, BaseRangeFilter,
  File "/libs/django_filters/filters.py", line 9, in <module>
    from django.db.models.sql.constants import QUERY_TERMS
ImportError: cannot import name 'QUERY_TERMS' from 'django.db.models.sql.constants' (/libs/django/db/models/sql/constants.py)
The command '/bin/sh -c python3 /bag-of-holding/project/manage.py makemigrations &&     python3 /bag-of-holding/project/manage.py migrate &&     python3 /bag-of-holding/project/manage.py loaddata /bag-of-holding/project/sample_data.json' returned a non-zero code: 1
```

Cheers,
fred

**Comment by aparsons** [comment]
@madchap I have a pretty good idea of what is causing the problem. Thanks for the bug report!

**Comment by aparsons** [comment]
@madchap Please give it another shot. I would highly appreciate it if you reported back if my fix worked or didn't. Thanks!

**Comment by madchap** [comment]
Hey,

Now fails with another error:

```
Traceback (most recent call last):
  File "/libs/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/libs/django/db/backends/sqlite3/base.py", line 321, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: no such table: boh_application__old

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/bag-of-holding/project/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/libs/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/libs/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/libs/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/libs/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/libs/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/libs/django/core/management/commands/loaddata.py", line 106, in loaddata
    connection.check_constraints(table_names=table_names)
  File "/libs/django/db/backends/sqlite3/base.py", line 287, in check_constraints
    column_name, referenced_column_name, column_name, referenced_column_name))
  File "/libs/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/libs/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/libs/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/libs/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/libs/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/libs/django/db/backends/sqlite3/base.py", line 321, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: Problem installing fixtures: no such table: boh_application__old
```

**Comment by aparsons** [comment]
@madchap I have pushed a change to the sample_data.json that was failing. From what I can tell, [there was an update to sqlite that broke this django version](https://groups.google.com/forum/?pli=1#!topic/django-updates/htVqH24DImg). I need to update the framework version in the near future, but this change should allow the docker container to be built and run. 

Again, if you can test it and give feedback I would appreciate it. Thanks!

**Comment by madchap** [comment]
All good now @aparsons, thanks :)
